// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/hero (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package mocks -destination ./internal/mocks/repository.go ./internal/domain/hero Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	hero "github.com/rodrigodip/fighting-fantasy/internal/domain/hero"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindByOwner mocks base method.
func (m *MockRepository) FindByOwner(userID string) (*hero.Hero, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwner", userID)
	ret0, _ := ret[0].(*hero.Hero)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwner indicates an expected call of FindByOwner.
func (mr *MockRepositoryMockRecorder) FindByOwner(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwner", reflect.TypeOf((*MockRepository)(nil).FindByOwner), userID)
}

// RegisterHero mocks base method.
func (m *MockRepository) RegisterHero(arg0 hero.Hero) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterHero", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterHero indicates an expected call of RegisterHero.
func (mr *MockRepositoryMockRecorder) RegisterHero(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHero", reflect.TypeOf((*MockRepository)(nil).RegisterHero), arg0)
}
