networks:
  mynet:

services:
    mongo:
        image: mongo:8
        container_name: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
          MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
          - mongo_data:/data/db
        # Sem expose de porta — não precisa ser acessível fora da rede interna
        networks:
          - mynet

    app:
        build:
          context: .
          dockerfile: Dockerfile
          target: build-production
        container_name: ffantasy_prod
        restart: always
        depends_on:
          - mongo
        # Sem volumes — imagem autossuficiente
        environment:
          - MONGO_URI=${MONGO_URI}
          - MONGO_DB=${MONGO_DB}
          - JWT_SECRET=${JWT_SECRET}
          - JWT_ISSUER=${JWT_ISSUER}
          - SET_ENVIRONMENT=production
          - SESSION_SECRET=${SESSION_SECRET}
          - HTTP_PORT=${HTTP_PORT}
          - SMTP_HOST=${SMTP_HOST}
          - SMTP_PORT=${SMTP_PORT}
          - SMTP_USERNAME=${SMTP_USERNAME}
          - SMTP_PASSWORD=${SMTP_PASSWORD}
          - SMTP_FROM=${SMTP_FROM}
          - WEB_TEMPLATE_PATH=${WEB_TEMPLATE_PATH}
        ports:
          - "8080:8080"
        networks:
          - mynet

volumes:
  mongo_data:
